version: '3.1'

services:
  symfony:
    build:
      context: ./build/Symfony
    restart: always
    ports:
      - 8888:8000
    # environment:
    volumes:
      - ./joke_test:/srv
  # db:
  #   image: mysql:5.7
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: exampledb
  #     MYSQL_USER: exampleuser
  #     MYSQL_PASSWORD: examplepass
  #     MYSQL_RANDOM_ROOT_PASSWORD: '1'
  #   volumes:
  #     - db:/var/lib/mysql

# volumes:
  # db:
