version: '3.1'

services:
  app:
    build:
      context: ./build/Symfony
    restart: always
    ports:
      - 8888:8000
    # environment:
    volumes:
      - ./joke_test:/srv/app
  node:
    image: node:10.21.0-alpine3.9
    volumes:
      - ./joke_test:/srv
    working_dir: /srv
